### ISSUE TITLE
Xeus-Python fails to work

### ISSUE THREAD

**Issue by Josh-Hiz** [jupyterlite/jupyterlite-sphinx#103]
## Description

I wanted to switch the kernels to use on my sphinx site to Xeus because I cant use the input() function with Pyodide, however even when redownloading Xeus with pip it fails to build and proceeds to tell me that it failed to create a virtual environment for xeus-python which makes no sense. 

## Reproduce

I am using the sphinx-book-theme for my site, and whenever I run 'make html' the following error will be provided:

```
RuntimeError: Failed to create the virtual environment for xeus-python,
        please make sure at least mamba, micromamba or conda is installed.
        
[LiteBuildApp] Exiting application: jupyter
```

## Expected behavior

It should simply build and I will be able to use the xeus-kernel only, as I cannot run Pyodide. 

## Context

- JupyterLite version: 0.1.0
- Operating System and version: Mac OS ventura 
- Browser and version: Google Chrome (latest version)

**Comment by martinRenou** [comment]
> that it failed to create a virtual environment for xeus-python which makes no sense.

It does make sense :)

In order to use the jupyterlite-xeus-python kernel with a custom environment, it will try to create that environment with either conda, mamba or micromamba depending on what you installed.

It should not try to create a custom environment if you did not add an `environment.yml` file in your docs. So you can either remove that file, or install either conda, mamba or micromamba in your docs build system.
