### ISSUE TITLE
Cannot change log level

### ISSUE THREAD

**Issue by drammock** [jupyterlite/jupyterlite-sphinx#112]
## Description

This extension generates more than 100 lines of build output in my terminal, which makes it harder to find other output that I'm more interested in (e.g. sphinx warnings). I want to set the log level somehow, but can't figure out how. I have placed a `jupyterlite_config.json` in the same directory as `conf.py` and it's getting loaded:

```
[LiteBuildApp] Loaded config file: /opt/pydata-sphinx-theme/docs/jupyterlite_config.json
```
Here's the content of that file:

```json
{
    "LiteBuildConfig": {
        "Application": {
            "log_level": 40
        }
    }
}
```

Inspired by [this](https://github.com/jupyterlite/jupyterlite/blob/2be4c063fa38e210956de8bfe75af5d8fb9ff535/py/jupyterlite-core/jupyterlite_core/tests/test_extend_addon.py#L21) I also tried 
```json
{
    "LiteBuildConfig": {
        "log_level": 40
    }
}
```
but that gives a warning:
```
[LiteBuildApp] WARNING | Config option `log_level` not recognized by `LiteManager`.
```

Any guidance on how to actually suppress the terminal output of LiteBuildApp?

## Reproduce

Sorry this is a complicated reproducer, I haven't had time to boil it down:

- clone https://github.com/drammock/pydata-sphinx-theme/tree/silence-warnings
- install `nox`
- run `nox -s docs`
- see the 100+ lines of `LiteBuildApp` output in the terminal that is not getting suppressed.

## Expected behavior

the 100+ lines of output will be suppressed

## Context

```console
$ mamba list jupyterlite
# packages in environment at /opt/mambaforge/envs/pst:
#
# Name                    Version                   Build  Channel
jupyterlite-core          0.1.3              pyhd8ed1ab_0    conda-forge
jupyterlite-sphinx        0.9.3              pyhd8ed1ab_0    conda-forge
$ uname -a
Linux agelaius 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```
Browser: N/A, this is about terminal output during build

**Comment by Carreau** [comment]
I believe this was taken care of by #153

**Comment by agriyakhetarpal** [comment]
@steppi, would it be a good idea to add a three-level (or less) logger and configure it? I feel it can be taken up in #162

**Comment by steppi** [comment]
> @steppi, would it be a good idea to add a three-level (or less) logger and configure it? I feel it can be taken up in #162

There's some prep work needed for that to actually help because the vast majority of noisy output comes upstream and can't  be controlled with a logger.

Some of the output comes for `doit` from within` jupyterlite_core`, the verbosity is hard coded, and we'd need to get them to allow this to be configured. See https://github.com/jupyterlite/jupyterlite/issues/1351.

Another source of noisy output is unguarded print statements in `jupyterlite_core/addons/` as described in https://github.com/jupyterlite/jupyterlite-sphinx/issues/149#issuecomment-2004635037. These would need to be changed to use a logger upstream.

If we actually want the log level to be configurable, this stuff needs to be changed upstream.
