### ISSUE TITLE
release the pin on Sphinx version ? 

### ISSUE THREAD

**Issue by 12rambau** [jupyterlite/jupyterlite-sphinx#83]
In the current implementation, jupyterlite-shinx enforces a Sphinx 4 version. Sphinx 6 is out since December and Sphinx 4 is starting to be dropped by other Sphinx extensions. 

Would it be possible to change/remove this pinned version from setup.py ?

**Comment by martinRenou** [comment]
Yes we could try updating the pin to `>=4,<6` :)

**Comment by lesteve** [comment]
I bumped into this while working on [sphinx-gallery Jupyterlite integration](https://github.com/sphinx-gallery/sphinx-gallery/pull/977) since sphinx-gallery is testing for a range of sphinx-version up the sphinx development version.

This is quite confusing right now that
```
pip install 'sphinx>6' jupyterlite-sphinx
```

will get you an old jupyterlite-sphinx version namely 0.4.0, which does not have the `config.jupyterlite_bind_ipynb_suffix` and so I spent quite some time figuring out why `jupyterlite_bind_ipynb_suffix` was not taken into account in some of the sphinx-gallery CI builds causing errors ...

**Comment by martinRenou** [comment]
> will get you an old jupyterlite-sphinx version namely 0.4.0

Yeah, this is because we did not have proper sphinx pinning at the time, we should have had the pin the entire time IMHO (not blaming anyone, I'm responsible for this I suppose). Let's release the pin then... Thanks for your PR!

**Comment by lesteve** [comment]
> Yeah, this is because we did not have proper sphinx pinning at the time

Yep, it does make sense given the constraints, but the behaviour for the user is still quite confusing. I guess this will be a lot better once there is a release with #85 in. In the meantime we can use a work-around.

In my case it took me a while to realise that it was the root cause, I thought that somehow the sphinx events were not happening in the right order.

> we should have had the pin the entire time IMHO

Just curious, would you mind saying a few words why? In my mind jupyterlite-sphinx is a library not an application and I would think it does not really need to pin its dependencies. Also the jupyterlite-sphinx, code does not seem to rely on too many sphinx internals so I would think that it is not that likely to break between Sphinx major releases.

**Comment by martinRenou** [comment]
> this will be a lot better once there is a release with https://github.com/jupyterlite/jupyterlite-sphinx/pull/85 in

jupyterlite-sphinx 0.7.3 is released :) You can use it

> Just curious, would you mind saying a few words why? In my mind jupyterlite-sphinx is a library not an application and I would think it does not really need to pin its dependencies. Also the jupyterlite-sphinx, code does not seem to rely on too many sphinx internals so I would think that it is not that likely to break between Sphinx major releases.

Nothing prevents Sphinx devs to release a v7 that breaks the plugins API assumptions and break jupyterlite-sphinx. I want to prevent that, and to prevent the user to have to deal with debugging (like you had to do). But because we did not have proper pinning the entire time you ended up in this annoying position, sorry for that!

**Comment by lesteve** [comment]
> jupyterlite-sphinx 0.7.3 is released :) You can use it

Nice thanks a lot for this!

It is true that my experience from working on sphinx-gallery a long time ago (things may have changed a bit since) was that Sphinx tended to break things a little too often in my biased opinion.
